npcs:
 '207': 'mark' #Айди нпс и название разговора

conversations:
  mark: #Вот тут имя разговора
    interceptor: packet,simple
    quester: "Марк" #Имя нпс в разговоре
    first: "npc1,npc5" #Тут назначаем какие диалоги из "NPC_options:" будут первыми
    stop: false
    NPC_options:
       npc1:
        text: "Помогите пожалуйта, мою ферму атаковали вредители."
        pointer: "player1" #Вот тут определяем на какой разговор из "player_options:" будет ссылаться этот разговор
        condition: '!has_tag_complete' #только уже тут перед условием ставим знак ! это будет означать что у игрока не должно быть этого тега!
       npc2:
        text: "Прошу убей их, они портят мою пшеницу, моя семья очень нуждаетя в еде."
        pointer: "player2,player3" #ТУТ ТАКЖЕ 
       npc3:
        text: "Спасибо что согласился!"
       npc4:
        text: "Жаль, что ты отказался."
       npc5:
        text: "Спасибо что помог!" 
        condition: 'has_tag_complete'  #ЭТО УСЛОВИЕ ЧТО ИГРОК ВЫПОЛНИЛ КВЕСТ И ПОЛУЧИЛ ТЕГ 
    player_options:
       player1:
        text: "Чем помочь?"
        pointer: "npc2" #ТУТ ТАКЖЕ 
       player2:
        text: "Хорошо, я помогу тебе."
        pointer: "npc3" #ТУТ ТАКЖЕ
        event: 'tag_and_obj' 
       player3:
        text: "Прости, но я занят"
        pointer: "npc4" #ТУТ ТАКЖЕ



events:
  reward: "money +10" #ЭТО НАГРДА 10 ВАЛЮТЫ
  reward1: mmoclassexperience 780 #ЭТО НАГРАДА ОПЫТ
  soundd: 'notify sound:ITEM_FIRECHARGE_USE'
  notify: "notify  \n &6Квест выполнен! \n &aВы заработали 780 опыта и 10 шекелей. \n "
  tag: tag add questStart
  give_obj: 'objective add NEGR_GAY'
  tag_and_obj: folder tag,give_obj
  tag_complete: tag add tag_complete
  
conditions: 
  WARRIOR: mmoclass WARRIOR
  has_tag: tag questStart 
  has_tag_complete: tag tag_complete

objectives:
  NEGR_GAY: mmobkill GOBLIN_PEST amount:6 events:reward,reward1,tag_complete,notify,soundd conditions:has_tag

menu_conv_io: #ЭТО ПРОСТ НАСТРОЙКИ РАЗГОВОРА ЕГО ПРОСТО СТАВИИШЬ В КОНЕЦ ЧТОБ НЕ МЕШАЛ
  line_length: 70
  refresh_delay: 180 
  selectionCooldown: 10

  npc_wrap: '&l &r' 
  npc_text: '&l &r&f{npc_text}' 
  npc_text_reset: '&f' 
  option_wrap: '&r&l &l &l &l &r' 
  option_text: '&l &l &l &l &r&8[ &b{option_text}&8 ]' 
  option_text_reset: '&b' 
  option_selected: '&l &r &r&a✔&r &8» &f&n{option_text}&8 «' 
  option_selected_reset: '&f' 
  option_selected_wrap: '&r&l &l &l &l &r&f&n'

  control_cancel: 'sneak'
  control_select: 'jump' 
  control_move: 'scroll,move' 

  npc_name_type: chat 
  npc_name_align: center 
  npc_name_format: '&e» &6{npc_name} &e«' 
  npc_name_newline_separator: true 
